targets:
  $default:
    builders:
      # `@JsonSerializable`-annotated class in the package.
      json_serializable:
        options:
          create_field_map: true #default false
          explicit_to_json: true #default false
          ignore_unannotated: true #default false
          include_if_null: false #default true
      dart_json_mapper:
        generate_for:
        # here should be listed entry point files having 'void main()' function
          - lib/main.dart

      # This part is needed to tell original reflectable builder to stay away
      # it overrides default options for reflectable builder to an **empty** set of files
      reflectable:
        generate_for:
          - no/files
