targets:
  $default:
    builders:
      # `@JsonSerializable`-annotated class in the package.
      json_serializable:
        options:
          create_field_map: true #default false
          explicit_to_json: true #default false
          ignore_unannotated: true #default false
          include_if_null: false #default true